### ISSUE TITLE
HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by Amyunimus** [NickHeiner/fitbit-export#12]
I'm getting the following error message when I try to download my data on Chrome (this is new as of today -- yesterday, I was getting the Unexpected Token error listed in the other issue. I still get this Unexpected Token error when I try to download the data on Safari). There is just over a year's worth of data in my fit-bit account. 

```
{
  "message": "Response code 401 (Unauthorized)",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/foods/log/caloriesIn/date/today/max.json",
  "statusCode": 401,
  "statusMessage": "Unauthorized",
  "requestUrl": "https://api.fitbit.com/1/user/-/foods/log/caloriesIn/date/today/max.json"
}
HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.e (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:114:13)
    at wrappedPromise.linkTransaction (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by registered99** [comment]
I'm getting this same issue. Did they revoke your API key?

**Comment by NickHeiner** [comment]
Posted https://community.fitbit.com/t5/Web-API/What-does-401-on-a-GET-mean/m-p/1574007#M6371 to inquire with Fitbit.

**Comment by NickHeiner** [comment]
@registered99 @Amyunimus Fitbit support asked me for more information on that thread. I've updated the code to provide that additional information. Can you try this again and let me know if you're still seeing the issue? If so, can you paste the full error output? Thanks!

**Comment by registered99** [comment]
This worked, thank you! No errors on my end.
