### ISSUE TITLE
Gateway Timeout (Code 504)

### ISSUE THREAD

**Issue by mohughes** [NickHeiner/fitbit-export#13]
Hi Nick,

I've just found your app, so this is my first attempt to grab my Fitbit data.  I have roughly three years of data to pull, if memory serves me right.  I'm receiving the error message below, as tested on OS X Yosemite via both Safari 9.1.3 and Firefox 48.0.2.  Any ideas?

Thanks,
Mitchell

```
{
  "message": "Unexpected token < in JSON at position 0 in \"https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/max.json\": \n<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\">...",
  "host": "api.fitbit.com",
  "hostname": "api.fitbit.com",
  "method": "GET",
  "path": "/1/user/-/activities/activityCalories/date/today/max.json",
  "statusCode": 504,
  "statusMessage": "Gateway Timeout",
  "requestUrl": "https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/max.json"
}

ParseError: Unexpected token < in JSON at position 0 in "https://api.fitbit.com/1/user/-/activities/activityCalories/date/today/max.json": 
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US">...
    at stream.catch.then.e (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\got\index.js:109:14)
    at wrappedPromise.linkTransaction (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:168:23)
    at wrappedPromise.wrapped [as __NR_wrapper] (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\transaction\tracer\index.js:155:28)
    at wrappedHandler (\\100.82.66.105\volume-3-default\71e539140aab05178a3f\76b230477a3846258950e7edbb2d6695\site\wwwroot\node_modules\newrelic\lib\instrumentation\core\globals.js:202:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by NickHeiner** [comment]
For some reason, the `activityCalories` endpoint appears to be bombing out. The others work fine. [I've followed up with Fitbit.](https://community.fitbit.com/t5/Web-API/504-Error-Code-for-activityCalories/m-p/1579598#M6393)

**Comment by NickHeiner** [comment]
Well, I "fixed" this by just removing the `activityCalories` endpoint in 9d2398b72abc11d96d54b867b7f46a6a288395b7. You should be able to get your data now.

**Comment by mohughes** [comment]
Thank you, Nick!  Problem solved.
